#!/bin/sh

BASE="/etc/s6-linux-init/current"

echo -e "\n  Initial startup..."

rm -rf "$BASE"
/bin/s6-linux-init-maker -p "/usr/sbin:/usr/bin:/sbin:/bin" -c "$BASE" "$BASE"
# Additional services, not under s6-rc control
mv "$BASE/../more-services/"* "$BASE/run-image/service" 2>/dev/null

cd "$BASE"/bin
mv init /sbin/init
for file in *; do
  cp "$file" "/sbin/${file}.s6"
  /usr/bin/update-alternatives \
     --install "/sbin/$file" "$file" "/sbin/${file}.s6" 200
done

cd /etc/s6-rc
if ! [ -d compiled ] && [ -d tree ]; then
  echo -e "\n  Initial compilation of RC dependencies"
  rm -rf compiledA
  rm -f compiled
  s6-rc-compile compiledA tree
  ln -s compiledA compiled
fi

ln -sf /run/service /service || :
sync
cd /
exec /sbin/init "$@"
