#!/bin/sh

# must be called with cwd==/etc/s6-rc/tree

for service in $@; do
  test -d "$service" || exit 1
  # Add service to any bundle listed in "${service}/bundles"
  if test -f "${service}/bundles"; then
    for bundle in $(cat "${service}/bundles"); do
      test -d "$bundle" || mkdir -p "${bundle}/contents.d"
      test -r "${bundle}/type" || echo "bundle" > "${bundle}/type"
      test $(cat "${bundle}/type") = "bundle" || exit 1

       : > "${bundle}/contents.d/${service}"
    done
  fi
  # Add service as dependency to any service listed in "${service}/influence"
  if test -f "${service}/influences"; then
    for influence in $(cat "${service}/influences"); do
      test -d "${influence}/dependencies.d" || exit 1
      : > "${influence}/dependencies.d/${service}"
    done
  fi
done
