#!/bin/sh -e

usage()
{
  echo "Usage $0 [enable|disable] service1 ...."
  exit 1
}

command="$1"
shift

test "$#" -ge 1 || usage

if test "$1" = default; then
  # protect the user from adding the
  # default bundle to the default bundle
  echo "Invalid service 'default'"
  usage
fi

for service in "$@"; do
  if test -z ${service%%*/*} || ! test -d "/etc/s6-rc/tree/$service"
  then
    echo "Unknown Service $service"
    usage
  fi
done

cd /etc/s6-rc/tree/default/contents.d

case "$command" in
  enable)  touch "$@" ;;
  disable) rm -f "$@" ;;
  *)       usage
esac

# Modify the compiled database
s6-rc-bundle -f add default *

# Activate the new "default" bundle
exec s6-rc -up -v2 change default
