MACHINE = "qemux86-64"
DISTRO = "nodistro"
DISTRO_FEATURES:remove = "ptest"
DISTRO_VERSION = "s6-test-distribution-1.0"
PACKAGE_CLASSES = "package_ipk"
TCLIBC = "musl"
INIT_MANAGER = "s6"
IMAGE_FSTYPES = "ext4"
QB_DEFAULT_FSTYPE = "ext4"
EXTRA_IMAGE_FEATURES = "\
    empty-root-password \
    allow-empty-password \
    allow-root-login \
"
